"""Init

Revision ID: ffe14e88dda8
Revises: f751864ca8c4
Create Date: 2023-01-14 18:25:51.566869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe14e88dda8'
down_revision = 'f751864ca8c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'disciplines', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('groups', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_constraint(None, 'disciplines', type_='foreignkey')
    # ### end Alembic commands ###
